\hypertarget{_underflow_exception_8h_source}{}\doxysection{C\+:/\+Users/\+Dulapah Vibulsanti/\+One\+Drive -\/ KMITL/\+Documents/\+Git\+Hub/\+Problem\+Set/\+KMITL\+\_\+\+C-\/\+CPP/\+Semester\+\_\+2/\+Lab8/\+Underflow\+Exception.h}

\begin{DoxyCode}{0}
\DoxyCodeLine{1 \textcolor{preprocessor}{\#pragma once}}
\DoxyCodeLine{2 }
\DoxyCodeLine{3 \textcolor{preprocessor}{\#include <iostream>}}
\DoxyCodeLine{4 \textcolor{preprocessor}{\#include <stdexcept>}}
\DoxyCodeLine{5 }
\DoxyCodeLine{6 \textcolor{keyword}{using namespace }std;}
\DoxyCodeLine{7 }
\DoxyCodeLine{8 \textcolor{comment}{//user defined class for handling exception}}
\DoxyCodeLine{9 }
\DoxyCodeLine{10 \textcolor{keyword}{class }\mbox{\hyperlink{class_underflow_exception}{UnderflowException}} : \textcolor{keyword}{public} runtime\_error \{}
\DoxyCodeLine{11 \textcolor{keyword}{public}:}
\DoxyCodeLine{12     \mbox{\hyperlink{class_underflow_exception}{UnderflowException}}()}
\DoxyCodeLine{13         : runtime\_error(\textcolor{stringliteral}{"{}Math error: Stack underflow\(\backslash\)n"{}}) \{}
\DoxyCodeLine{14     \}}
\DoxyCodeLine{15 \};}

\end{DoxyCode}
